#############################################################################
# Makefile for building: fractal
# Generated by qmake (1.07a) (Qt 3.3.4) on: Thu Jun  8 11:13:30 2006
# Project:  fractal.pro
# Template: app
# Command: $(QMAKE) -o Makefile fractal.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -Wall -W -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -m32 -march=i386 -mtune=pentium4 -fasynchronous-unwind-tables  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT
CXXFLAGS = -pipe -Wall -W -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -m32 -march=i386 -mtune=pentium4 -fasynchronous-unwind-tables  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/lib/qt-3.3/mkspecs/default -I. -I$(QTDIR)/include -I.ui/ -I. -I.moc/
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS) -L$(QTDIR)/lib -L/usr/X11R6/lib -pthread -llammpio -llammpi++ -llamf77mpi -lmpi -llam -lutil -ldl -lqt-mt -lXext -lX11 -lm
AR       = ar cqs
RANLIB   = 
MOC      = $(QTDIR)/bin/moc
UIC      = $(QTDIR)/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = .obj/

####### Files

HEADERS = fractal.h \
		metadata.h \
		structureparser.h \
		computation.h \
		helpwindow.h
SOURCES = main.cpp \
		fractal.cpp \
		metadata.cpp \
		structureparser.cpp \
		computation.cpp \
		helpwindow.cpp
OBJECTS = .obj/main.o \
		.obj/fractal.o \
		.obj/metadata.o \
		.obj/structureparser.o \
		.obj/computation.o \
		.obj/helpwindow.o \
		.obj/mainform.o \
		.obj/qmake_image_collection.o
FORMS = mainform.ui
UICDECLS = .ui/mainform.h
UICIMPLS = .ui/mainform.cpp
SRCMOC   = .moc/moc_fractal.cpp \
		.moc/moc_helpwindow.cpp \
		.moc/moc_mainform.cpp
OBJMOC = .obj/moc_fractal.o \
		.obj/moc_helpwindow.o \
		.obj/moc_mainform.o
DIST	   = fractal.pro
QMAKE_TARGET = fractal
DESTDIR  = 
TARGET   = fractal

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: fractal.pro  /usr/lib/qt-3.3/mkspecs/default/qmake.conf /usr/lib/qt-3.3/lib/libqt-mt.prl
	$(QMAKE) -o Makefile fractal.pro
qmake: 
	@$(QMAKE) -o Makefile fractal.pro

dist: 
	@mkdir -p .obj/fractal && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .obj/fractal/ && $(COPY_FILE) --parents images/gtk/gtk-redo.png images/gtk/gnome-unknown.png images/gtk/gtk-print.png images/gtk/gtk-save-as.png images/gtk/gtk-save.png images/gtk/gtk-stock-fullscreen.png images/gtk/gtk-undo.png images/gtk/panel-logout.png images/gtk/stock-import.png images/gtk/stock-new.png images/gtk/stock-open.png images/gtk/stock-zoom-in.png images/gtk/stock-zoom-out.png images/gtk/handbook.png images/gtk/gtk-refresh.png .obj/fractal/ && $(COPY_FILE) --parents mainform.ui.h .obj/fractal/ && ( cd `dirname .obj/fractal` && $(TAR) fractal.tar fractal && $(GZIP) fractal.tar ) && $(MOVE) `dirname .obj/fractal`/fractal.tar.gz . && $(DEL_FILE) -r .obj/fractal

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:
	-$(DEL_FILE) $(UICIMPLS) $(UICDECLS)

yaccclean:
lexclean:
clean: mocclean uiclean
	-$(DEL_FILE) $(OBJECTS)
		-$(DEL_FILE) .ui/qmake_image_collection.cpp
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

.obj/main.o: main.cpp fractal.h \
		computation.h \
		metadata.h \
		.ui/mainform.h \
		structureparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/main.o main.cpp

.obj/fractal.o: fractal.cpp fractal.h \
		helpwindow.h \
		computation.h \
		.ui/mainform.h \
		metadata.h \
		structureparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/fractal.o fractal.cpp

.obj/metadata.o: metadata.cpp metadata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/metadata.o metadata.cpp

.obj/structureparser.o: structureparser.cpp structureparser.h \
		metadata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/structureparser.o structureparser.cpp

.obj/computation.o: computation.cpp computation.h \
		metadata.h \
		fractal.h \
		.ui/mainform.h \
		structureparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/computation.o computation.cpp

.obj/helpwindow.o: helpwindow.cpp helpwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/helpwindow.o helpwindow.cpp

.ui/mainform.h: mainform.ui 
	$(UIC) mainform.ui -o .ui/mainform.h

.ui/mainform.cpp: .ui/mainform.h mainform.ui mainform.ui.h 
	$(UIC) mainform.ui -i mainform.h -o .ui/mainform.cpp

.obj/mainform.o: .ui/mainform.cpp mainform.ui.h \
		.ui/mainform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/mainform.o .ui/mainform.cpp

.obj/moc_fractal.o: .moc/moc_fractal.cpp  fractal.h .ui/mainform.h \
		metadata.h \
		structureparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_fractal.o .moc/moc_fractal.cpp

.obj/moc_helpwindow.o: .moc/moc_helpwindow.cpp  helpwindow.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_helpwindow.o .moc/moc_helpwindow.cpp

.obj/moc_mainform.o: .moc/moc_mainform.cpp  .ui/mainform.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_mainform.o .moc/moc_mainform.cpp

.moc/moc_fractal.cpp: $(MOC) fractal.h
	$(MOC) fractal.h -o .moc/moc_fractal.cpp

.moc/moc_helpwindow.cpp: $(MOC) helpwindow.h
	$(MOC) helpwindow.h -o .moc/moc_helpwindow.cpp

.moc/moc_mainform.cpp: $(MOC) .ui/mainform.h
	$(MOC) .ui/mainform.h -o .moc/moc_mainform.cpp

.obj/qmake_image_collection.o: .ui/qmake_image_collection.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/qmake_image_collection.o .ui/qmake_image_collection.cpp

.ui/qmake_image_collection.cpp: images/gtk/gtk-redo.png \
		images/gtk/gnome-unknown.png \
		images/gtk/gtk-print.png \
		images/gtk/gtk-save-as.png \
		images/gtk/gtk-save.png \
		images/gtk/gtk-stock-fullscreen.png \
		images/gtk/gtk-undo.png \
		images/gtk/panel-logout.png \
		images/gtk/stock-import.png \
		images/gtk/stock-new.png \
		images/gtk/stock-open.png \
		images/gtk/stock-zoom-in.png \
		images/gtk/stock-zoom-out.png \
		images/gtk/handbook.png \
		images/gtk/gtk-refresh.png
	$(UIC)  -embed fractal images/gtk/gtk-redo.png images/gtk/gnome-unknown.png images/gtk/gtk-print.png images/gtk/gtk-save-as.png images/gtk/gtk-save.png images/gtk/gtk-stock-fullscreen.png images/gtk/gtk-undo.png images/gtk/panel-logout.png images/gtk/stock-import.png images/gtk/stock-new.png images/gtk/stock-open.png images/gtk/stock-zoom-in.png images/gtk/stock-zoom-out.png images/gtk/handbook.png images/gtk/gtk-refresh.png -o .ui/qmake_image_collection.cpp

####### Install

install:  

uninstall:  

